modLoader="kotlinforforge"
loaderVersion="[1.3,1.4)"

[[mods]]
modId="throwable"
version="1.0"
displayName="Throwable"
credits="Thanks to KotlinForForge for making this mod possible with kotlin."
authors="Enterman"

description='''
Throw blocks.
'''

[[dependencies.throwable]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.throwable]]
 #   modId="kotlinforforge"
  #  mandatory=true
   # versionRange="[1.3.1,)"
    #ordering="NONE"
     #side="BOTH"
